name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - v2_wip
    paths:
      - ".github/workflows/pip.yml"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools numpy gsd networkx biopython matplotlib

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: |
        cd tests
        python -m pytest